const TEXTS = {
  ua: {
    welcome: "🔥 *WAP CLUB :: MOBILE DETAILING*\n\nІнженерний підхід до естетики вашого авто. Ми працюємо на виїзді у Кропивницькому — повністю автономно.\n\n👇 *Оберіть розділ:*",
    btn_detailing: "🚗 Виїзний детейлінг", btn_polishing: "✨ Полірування фар", btn_chips: "🛠 Ремонт сколів",
    btn_about: "ℹ️ Про клуб / Портфоліо", btn_contact: "💬 Зв'язок з інженером", btn_back: "🔙 У головне меню",
    btn_back_packages: "🔙 До пакетів", btn_next_carclass: "➡️ Далі: клас авто",
    btn_order: "✅ Замовити (Крок 1: Контакт)", btn_share_phone: "📱 Поділитися номером телефону",
    ask_phone: "📞 Майже готово! Натисніть кнопку нижче, щоб поділитися номером телефону для зв'язку з майстром:",
    order_success: "✅ *Заявку підтверджено!*\n\nНомер заявки: `{orderId}`\n📞 Телефон: `{phone}`\n🛠 Послуга: *{service}*\n💰 Вартість: *{price} грн*\n📅 Дата заявки: {date}\n\n👨‍🔧 Головний інженер зв'яжеться з вами протягом 10 хвилин для узгодження часу виїзду.",
    processing: "⏳ *Оформлюємо заявку...*",
    about: "🛡 *WAP CLUB — Це не звичайна мийка*\n\nМи побудували автономний мобільний комплекс. Нам не потрібна ваша розетка чи водопровід — у нас на борту власний бак з водою на 150л, інверторна система на 72V та професійна хімія.\n\n*Наші стандарти:*\n🔹 Безконтактна делікатна мийка\n🔹 Використання пензлів та очищення важкодоступних місць\n🔹 Захисні покриття для кузова та пластику",
    detailing_intro: "🚗 *ВИЇЗНИЙ ДЕТЕЙЛІНГ — ОБЕРІТЬ ПАКЕТ*\n\nТри рівні залежно від того, скільки часу та уваги потрібно вашому авто:",
    pkg_basic_title: "🅱️ Базовий пакет",
    pkg_basic_desc: "🅱️ *БАЗОВИЙ ПАКЕТ*\n\n• Безконтактна мийка кузова\n• Очищення дисків\n• Протирання скла та дзеркал\n\n⏱ *Час:* ~40-60 хв\n💰 *Базова вартість:* від 1000 грн\n_(фінальна ціна залежить від класу авто)_",
    pkg_standard_title: "🅂 Стандартний пакет",
    pkg_standard_desc: "🅂 *СТАНДАРТНИЙ ПАКЕТ*\n\n• Двофазна мийка, очищення пензлями\n• Прибирання салону, пилосос, скло\n• Консервація шин та пластику\n\n⏱ *Час:* 1.5 - 2.5 години\n💰 *Базова вартість:* від 1500 грн\n_(фінальна ціна залежить від класу авто)_",
    pkg_exclusive_title: "🅴 Ексклюзивний пакет",
    pkg_exclusive_desc: "🅴 *ЕКСКЛЮЗИВНИЙ ПАКЕТ*\n\n• Все зі стандартного пакету\n• Глибоке очищення салону та шкіри\n• Захисне покриття кузова (віск/кераміка-спрей)\n• Полірування пластикових елементів салону\n\n⏱ *Час:* 3 - 4 години\n💰 *Базова вартість:* від 2200 грн\n_(фінальна ціна залежить від класу авто)_",
    polishing_desc: "✨ *ГЛИБОКЕ ПОЛІРУВАННЯ ФАР*\n\n• Шліфування абразивами\n• Багатоступеневе полірування\n• Захисне покриття від ультрафіолету\n\n⏱ *Час:* ~1 година\n💰 *Базова вартість:* від 800 грн\n_(фінальна ціна залежить від класу авто)_",
    chips_desc: "🛠 *РЕМОНТ СКОЛІВ ТА ТРІЩИН*\n\nТочкове усунення сколів до появи корозії.\n\n💰 *Базова вартість:* від 500 грн\n_(фінальна ціна залежить від класу авто)_",
    contact_info: "📲 *Прямий зв'язок з майстром:*\nДля консультації напишіть нам напряму: @zabrodni_y",
    invalid_price: "⚠️ *Введіть коректну суму числом (наприклад: 1200):*",
    carclass_intro: "🚙 *ОБЕРІТЬ КЛАС АВТО*\n\nВід класу залежить фінальна вартість послуги:",
    cls_sedan: "🚗 Седан", cls_crossover: "🚙 Кросовер", cls_suv: "🚐 Позашляховик",
    order_summary: "📋 *ПІДСУМОК ЗАМОВЛЕННЯ*\n\n🛠 Послуга: *{service}*\n🚙 Клас авто: *{carclass}*\n💰 *Фінальна вартість: {price} грн*",
    btn_confirm_saved_phone: "✅ Підтвердити (номер: {phone})",
    btn_change_phone: "✏️ Змінити номер",
    btn_confirm_order: "✅ Замовити",
    review_request: "🏁 Ваше замовлення завершено!\n\n⭐ Будь ласка, оцініть якість роботи майстра від 1 до 5:",
    review_thanks: "Дякуємо за вашу оцінку {rating}! 🙏\nБудемо раді бачити вас знову.",
    review_thanks_high: "🎉 Дякуємо за високу оцінку {rating}! Дуже приємно це чути!",
    review_maps_prompt: "Якщо не складно, залиште, будь ласка, відгук на Google Maps — це дуже допомагає нам:",
    review_thanks_low: "😔 Нам дуже шкода, що щось пішло не так. Ваш відгук передано керівнику — ми обов'язково зв'яжемося з вами, щоб виправити ситуацію.",
    referral_welcome: "🎁 Вітаємо! Вам надано знижку 10% на перше замовлення як другу учасника клубу.",
    ltv_reminder: "Вітаємо, {name}! Минуло {days} днів з вашого останнього візиту до WAP CLUB 🚗 Захисне покриття вже потребує оновлення. Запишемо вас на освіжаючий догляд зі знижкою 10% як постійному клієнту?",
    myref_screen: "🎁 *Запросіть друга*\n\nВаше особисте посилання:\n{link}\n\nКоли друг перейде за посиланням і завершить своє перше замовлення — вам нарахується +150 грн бонусів. Другу одразу дається знижка 10% на перше замовлення.\n\n💰 *Ваш поточний баланс бонусів:* {balance} грн\n_(бонусами можна оплатити до 50% вартості наступного замовлення)_",
    btn_myref: "🎁 Запросити друга / Мій баланс"
  },
  en: {
    welcome: "🔥 *WAP CLUB :: MOBILE DETAILING*\n\nEngineering approach to your car's aesthetics. Mobile detailing in Kropyvnytskyi — fully autonomous.\n\n👇 *Choose section:*",
    btn_detailing: "🚗 Mobile Detailing", btn_polishing: "✨ Headlight Polishing", btn_chips: "🛠 Chip Repair",
    btn_about: "ℹ️ About Club / Portfolio", btn_contact: "💬 Contact Engineer", btn_back: "🔙 Main Menu",
    btn_back_packages: "🔙 Back to packages", btn_next_carclass: "➡️ Next: car class",
    btn_order: "✅ Order (Step 1: Contact)", btn_share_phone: "📱 Share Phone Number",
    ask_phone: "📞 Almost done! Tap the button below to share your phone number:",
    order_success: "✅ *Order confirmed!*\n\nOrder ID: `{orderId}`\n📞 Phone: `{phone}`\n🛠 Service: *{service}*\n💰 Price: *{price} UAH*\n📅 Order date: {date}\n\n👨‍🔧 Chief Engineer will contact you within 10 minutes to arrange the visit time.",
    processing: "⏳ *Processing your order...*",
    about: "🛡 *WAP CLUB — Premium Mobile Detailing*\n\nAutonomous mobile unit equipped with 150L water tank, 72V inverter system, and professional detailing products.\n\n*Our Standards:*\n🔹 Touchless delicate wash\n🔹 Detail brushes & thorough cleaning\n🔹 Protective coatings",
    detailing_intro: "🚗 *MOBILE DETAILING — CHOOSE A PACKAGE*\n\nThree levels depending on how much time and attention your car needs:",
    pkg_basic_title: "🅱️ Basic Package",
    pkg_basic_desc: "🅱️ *BASIC PACKAGE*\n\n• Touchless exterior wash\n• Wheel cleaning\n• Glass & mirror wipe-down\n\n⏱ *Time:* ~40-60 min\n💰 *Base price:* from 1000 UAH\n_(final price depends on car class)_",
    pkg_standard_title: "🅂 Standard Package",
    pkg_standard_desc: "🅂 *STANDARD PACKAGE*\n\n• Two-phase wash, detail brushes\n• Interior vacuum, glass cleaning\n• Tire & plastic dressing\n\n⏱ *Time:* 1.5 - 2.5 hours\n💰 *Base price:* from 1500 UAH\n_(final price depends on car class)_",
    pkg_exclusive_title: "🅴 Exclusive Package",
    pkg_exclusive_desc: "🅴 *EXCLUSIVE PACKAGE*\n\n• Everything in Standard\n• Deep interior & leather cleaning\n• Protective body coating (wax/ceramic spray)\n• Interior plastic polishing\n\n⏱ *Time:* 3 - 4 hours\n💰 *Base price:* from 2200 UAH\n_(final price depends on car class)_",
    polishing_desc: "✨ *HEADLIGHT POLISHING*\n\n• Abrasive sanding\n• Multi-step polishing\n• UV protection layer\n\n⏱ *Time:* ~1 hour\n💰 *Base price:* from 800 UAH\n_(final price depends on car class)_",
    chips_desc: "🛠 *CHIP & CRACK REPAIR*\n\nSpot repair of paint chips before corrosion occurs.\n\n💰 *Base price:* from 500 UAH\n_(final price depends on car class)_",
    contact_info: "📲 *Direct contact:*\nWrite directly to our engineer: @zabrodni_y",
    invalid_price: "⚠️ *Please enter a valid numeric amount (e.g. 1200):*",
    carclass_intro: "🚙 *CHOOSE YOUR CAR CLASS*\n\nThe final price depends on the vehicle class:",
    cls_sedan: "🚗 Sedan", cls_crossover: "🚙 Crossover", cls_suv: "🚐 SUV",
    order_summary: "📋 *ORDER SUMMARY*\n\n🛠 Service: *{service}*\n🚙 Car class: *{carclass}*\n💰 *Final price: {price} UAH*",
    btn_confirm_saved_phone: "✅ Confirm (phone: {phone})",
    btn_change_phone: "✏️ Change number",
    btn_confirm_order: "✅ Order now",
    review_request: "🏁 Your order is complete!\n\n⭐ Please rate the quality of work from 1 to 5:",
    review_thanks: "Thanks for your rating {rating}! 🙏\nHope to see you again.",
    review_thanks_high: "🎉 Thank you for the great rating {rating}! Wonderful to hear!",
    review_maps_prompt: "If it's not too much trouble, please leave a review on Google Maps — it really helps us:",
    review_thanks_low: "😔 We're very sorry something went wrong. Your feedback has been sent to management — we'll reach out to make it right.",
    referral_welcome: "🎁 Welcome! You've been given a 10% discount on your first order as a friend of a club member.",
    ltv_reminder: "Hi {name}! It's been {days} days since your last visit to WAP CLUB 🚗 Your protective coating could use a refresh. Shall we book you in for a touch-up with a 10% loyal-client discount?",
    myref_screen: "🎁 *Invite a friend*\n\nYour personal link:\n{link}\n\nWhen a friend follows the link and completes their first order, you get +150 UAH in bonus credit. Your friend gets 10% off their first order right away.\n\n💰 *Your current bonus balance:* {balance} UAH\n_(bonuses can cover up to 50% of your next order)_",
    btn_myref: "🎁 Invite a friend / My balance"
  }
};

module.exports = TEXTS;
